database/forms.py
# File written by Daniel E, Asha
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField
from wtforms.validators import InputRequired, ValidationError


def is_real(form, number):
    # Check if a number is within a specified range (0 to 99,999)
    if number.data < 0 or number.data > 99999:
        raise ValidationError('Number must be between 0 and 100000')


def validate_category(form, category):
    # Check if a category is either "food" or "hygiene"
    if category.data.lower() != "food" and category.data.lower() != "hygiene":
        raise ValidationError('category must be "food" or "hygiene"')


class ProductForm(FlaskForm):
    """
    Creates product form
    """
    name = StringField(validators=[InputRequired()])
    stock = IntegerField(validators=[InputRequired(),
                                     is_real])
    category = StringField(validators=[InputRequired(),
                                       validate_category])
    required_stock = IntegerField(validators=[InputRequired(),
                                              is_real])
    submit = SubmitField()


class RequiredStockForm(FlaskForm):
    """
    Creates required stock form
    """
    new_level = IntegerField(validators=[InputRequired(), is_real])
    submit = SubmitField()

database/views.py
#File Written by Daniel E, Najihah, Asha, Daniel C
from flask import request
from Database_Manager.db_crud import DbManager, ProductNotFoundError
from flask import Blueprint, render_template
from flask_login import login_required
from app import access_level_required
from database.forms import ProductForm, RequiredStockForm

database_blueprint = Blueprint('database', __name__, template_folder='templates')


@database_blueprint.route('/database', methods=['GET', 'POST'])
@login_required
@access_level_required('admin', 'user')
def database():
    """
    Sends to the database page
    :return: database.html
    """
    return render_template('database/database.html')


# View function for querying on the database page
@database_blueprint.route('/query', methods=['GET', 'POST'])
@login_required
@access_level_required('admin', 'user')
def query():
    """
    Get the query from the database
    :return: query_results.html
    """
    # Get a query from search_string
    search_string = request.args.get("search_string")
    # If the string is not empty, call query_products method from DbManager class
    if search_string:
        results = DbManager.query_products(search_string)
    # If empty, call get_all_product methods
    else:
        db = DbManager()
        results = db.get_all_products()

    return render_template("database/query_results.html", results=results)


@database_blueprint.route('/<int:product_id>/<int:mode>/adjust_stock', methods=['GET', 'POST'])
@login_required
@access_level_required('admin', 'user')
def adjust_stock(product_id, mode):
    """
    Adjust stock in the database
    :return: database.html
    """
    db = DbManager()
    # try method to handle potential exceptions
    try:
        # calls adjust_stock method from DbManager
        db.adjust_stock(product_id, mode)
    except (ValueError, ProductNotFoundError):
        pass
    search_string = request.args.get("search_string")
    # If search_string is not empty, it queries the database for matching products
    if search_string:
        results = DbManager.query_products(search_string)
    else:
        # sets results to empty list
        results = []

    return render_template("database/database.html", results=results)


@database_blueprint.route('/<int:product_id>/<int:current_level>/change_reorder_level', methods=['GET', 'POST'])
@login_required
@access_level_required('admin')
def change_reorder_level(product_id, current_level):
    """
    Allow the admin to change the reorder level of products
    :return: change_reorder_level.html
    """

    form = RequiredStockForm()

    if form.validate_on_submit():
        db = DbManager()
        # change stock level with check it can't be below zero
        try:
            db.change_stock_required_level(product_id, form.new_level.data)
        except (ValueError, ProductNotFoundError):
            pass
        return render_template("database/database.html")

    return render_template('database/change_reorder_level.html', form=form, current_level=current_level)


@database_blueprint.route('/add_product', methods=['GET', 'POST'])
@login_required
@access_level_required('admin', 'user')
def add_product():
    """
    Add new products to the database
    :return: add_product.html
    """
    form = ProductForm()

    if form.validate_on_submit():
        db = DbManager()
        db.add_product(form.name.data,
                       form.stock.data,
                       form.category.data,
                       form.required_stock.data)
        return render_template("database/database.html")

    return render_template('database/add_product.html', form=form)

# View function for the delete product feature on the database page
@database_blueprint.route('/<int:product_id>/delete_product', methods=['GET', 'POST'])
@login_required
@access_level_required('admin')
def delete_product(product_id):
    """
    Delete product from the database
    :return: database.html
    """
    db = DbManager()
    try:
        db.delete_product(product_id)
    except ProductNotFoundError:
        pass
    search_string = request.args.get("search_string")
    # If search_string is not empty, it queries the database for matching products
    if search_string:
        results = DbManager.query_products(search_string)

    else:
        #  sets results to empty list
        results = []

    return render_template("database/database.html", results=results)

templates/database/add_product.html
<!-- Written by Daniel Cook, Daniel Ellam, Megat Aiman, Asha Smeaton, Najihah Azman -->
{%  extends "base.html" %}

{% block content %}
<!-- Header -->
    <div class="column is-6 is-offset-3">
        <h1 class="center-h1">{% block title %} Add Product {% endblock %}</h1>
<!-- Accept input to add products to the database -->
    <div class="box"></div></div>
        <form method="POST">
            <!-- Accept input for Product Name -->
            <div class="field">
                {{  form.csrf_token() }}
                <div class = "control">
                    {{ form.name(class="center-input", placeholder="Product Name") }}
                    {% for error in form.name.errors %}
                        <div class="center-flash">
                            {{ error }}
                        </div>
                    {% endfor %}
                </div>
            </div>
            <!-- Accept input for Stock Level -->
            <div class="field">
                <div class = "control">
                    {{ form.stock(class="center-input", placeholder="Stock Level") }}
                    {% for error in form.stock.errors %}
                        <div class="center-flash">
                            {{ error }}
                        </div>
                    {% endfor %}
                </div>
            </div>
            <!-- Accept input for Category of the item-->
            <div class="field">
                <div class = "control">
                    {{ form.category(class="center-input", placeholder="Category (food/hygiene)") }}
                    {% for error in form.category.errors %}
                        <div class="center-flash">
                            {{ error }}
                        </div>
                    {% endfor %}
                </div>
            </div>
            <!-- Accept input for Required Stock Level -->
            <div class="field">
                <div class = "control">
                    {{ form.required_stock(class="center-input", placeholder="Required Stock Level") }}
                    {% for error in form.required_stock.errors %}
                        <div class="center-flash">
                            {{ error }}
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="box">
                {{  form.submit(class="add-btn") }}
            </div>
        </form>

{%  endblock %}

templates/database/change_reorder_level.html
<!-- Written by Daniel Cook, Daniel Ellam, Megat Aiman, Asha Smeaton -->
{%  extends "base.html" %}

{% block content %}

    <div class="column is-6 is-offset-3">
        <h1>{% block title %} Change Order Level {% endblock %}</h1>
        <br>
        <br>
        <br>
        <!-- Displays current order level of item -->
        <div class="change-order-level-box">
            <div class="box"> Current reorder level: {{ current_level }} </div>
        </div>
    <div class="box"></div></div>
        <form method="POST">
            <!-- Input for the new order level -->
            <div class="field">
                {{  form.csrf_token() }}
                <div class = "control">
                    {{ form.new_level(class="center-input", placeholder="New Level") }}
                    {% for error in form.new_level.errors %}
                        <div class="center-flash">
                            {{ error }}
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="box">
                {{  form.submit(class="button is-infor is-centered") }}
            </div>
        </form>
    </div>

{%  endblock %}

templates/database/database.html
<!-- Written by Daniel Cook, Daniel Ellam, Megat Aiman, Asha Smeaton, Najihah Azman -->
{% extends "base.html" %}

{% block content %}
    <!-- Header -->
    <div class="column is-6 is-offset-3">
        <h1 class="center-h1">{% block title %} Database {% endblock %}</h1>
        <br>
        <!-- Display table -->
        <div hx-get="/query" hx-trigger="load" hx-target="#results"></div>
        <h3><input type="text" class="input search-input" placeholder="Search" name="search_string" hx-get="/query" hx-trigger="keyup changed delay:500ms" hx-target="#results"></h3>
        <br>
        <table class="database-table">
            <tbody>
                <tr>
                    <th>Product Name</th>
                    <th>Remove Stock</th>
                    <th>Current Stock</th>
                    <th>Add Stock</th>
                    <th>Reorder Level</th>
                    <th>Category</th>
                    {% if current_user.is_authenticated and current_user.access_level=='admin' %}
                    <th>Delete Product</th>
                    {% endif %}
                </tr>
            </tbody>
            <tbody id="results">
            </tbody>
        </table>
        <!-- Add product button -->
        <br>
        <h3>
        <button class="add-product-btn" onclick="window.location.href='{{ url_for('database.add_product') }}'" style="background-color: blue; color: white; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer;">
            Add Product
        </button>
        </h3>
    </div>

{% endblock %}

templates/database/query_results.html
<!-- Written by Daniel Cook, Daniel Ellam, Najihah Azman -->
{% for result in results %}
    <!-- Generates a table that displays a list of products and their details -->
<tr>
    <td>{{ result.product }}</td>
    <td>
        <a class="btn-custom-subtract" href="{{ url_for('database.adjust_stock', product_id=result.product_id, mode=0) }}">-</a>
    </td>
    <td>{{ result.stock }}</td>
    <td>
        <a class="btn-custom-add" href="{{ url_for('database.adjust_stock', product_id=result.product_id, mode=1) }}">+</a>
    </td>
    {% if current_user.is_authenticated and current_user.access_level == 'admin' %}
    <td>
        <a class="btn-custom-level" href="{{ url_for('database.change_reorder_level', product_id=result.product_id, current_level=result.required_level) }}">{{ result.required_level }}</a>
    </td>
    {% else %}
    <td>{{ result.required_level }}</td>
    {% endif %}
    <td>{{ result.category }}</td>
    {% if current_user.is_authenticated and current_user.access_level == 'admin' %}
    <td>
        <a class="btn-custom-subtract" href="{{ url_for('database.delete_product', product_id=result.product_id) }}">Delete Row</a>
    </td>
    {% endif %}
</tr>
{% endfor %}