database/views.py
#File Written by Daniel E, Najihah, Asha, Daniel C
from flask import request
from Database_Manager.db_crud import DbManager, ProductNotFoundError
from flask import Blueprint, render_template
from flask_login import login_required
from app import access_level_required
from database.forms import ProductForm, RequiredStockForm

database_blueprint = Blueprint('database', __name__, template_folder='templates')


@database_blueprint.route('/database', methods=['GET', 'POST'])
@login_required
@access_level_required('admin', 'user')
def database():
    """
    Sends to the database page
    :return: database.html
    """
    return render_template('database/database.html')


# View function for querying on the database page
@database_blueprint.route('/query', methods=['GET', 'POST'])
@login_required
@access_level_required('admin', 'user')
def query():
    """
    Get the query from the database
    :return: query_results.html
    """
    # Get a query from search_string
    search_string = request.args.get("search_string")
    # If the string is not empty, call query_products method from DbManager class
    if search_string:
        results = DbManager.query_products(search_string)
    # If empty, call get_all_product methods
    else:
        db = DbManager()
        results = db.get_all_products()

    return render_template("database/query_results.html", results=results)


@database_blueprint.route('/<int:product_id>/<int:mode>/adjust_stock', methods=['GET', 'POST'])
@login_required
@access_level_required('admin', 'user')
def adjust_stock(product_id, mode):
    """
    Adjust stock in the database
    :return: database.html
    """
    db = DbManager()
    # try method to handle potential exceptions
    try:
        # calls adjust_stock method from DbManager
        db.adjust_stock(product_id, mode)
    except (ValueError, ProductNotFoundError):
        pass
    search_string = request.args.get("search_string")
    # If search_string is not empty, it queries the database for matching products
    if search_string:
        results = DbManager.query_products(search_string)
    else:
        # sets results to empty list
        results = []

    return render_template("database/database.html", results=results)


@database_blueprint.route('/<int:product_id>/<int:current_level>/change_reorder_level', methods=['GET', 'POST'])
@login_required
@access_level_required('admin')
def change_reorder_level(product_id, current_level):
    """
    Allow the admin to change the reorder level of products
    :return: change_reorder_level.html
    """

    form = RequiredStockForm()

    if form.validate_on_submit():
        db = DbManager()
        # change stock level with check it can't be below zero
        try:
            db.change_stock_required_level(product_id, form.new_level.data)
        except (ValueError, ProductNotFoundError):
            pass
        return render_template("database/database.html")

    return render_template('database/change_reorder_level.html', form=form, current_level=current_level)


@database_blueprint.route('/add_product', methods=['GET', 'POST'])
@login_required
@access_level_required('admin', 'user')
def add_product():
    """
    Add new products to the database
    :return: add_product.html
    """
    form = ProductForm()

    if form.validate_on_submit():
        db = DbManager()
        db.add_product(form.name.data,
                       form.stock.data,
                       form.category.data,
                       form.required_stock.data)
        return render_template("database/database.html")

    return render_template('database/add_product.html', form=form)

# View function for the delete product feature on the database page
@database_blueprint.route('/<int:product_id>/delete_product', methods=['GET', 'POST'])
@login_required
@access_level_required('admin')
def delete_product(product_id):
    """
    Delete product from the database
    :return: database.html
    """
    db = DbManager()
    try:
        db.delete_product(product_id)
    except ProductNotFoundError:
        pass
    search_string = request.args.get("search_string")
    # If search_string is not empty, it queries the database for matching products
    if search_string:
        results = DbManager.query_products(search_string)

    else:
        #  sets results to empty list
        results = []

    return render_template("database/database.html", results=results)

users/views.py
# File written by Daniel, Megat, Louis, Asha
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import login_user, current_user, login_required, logout_user
from app import access_level_required
from users.forms import LoginForm, RegisterForm, UpdatePasswordForm
from Database_Manager.db_crud import DbManager, UserNotFoundError

users_blueprint = Blueprint('users', __name__, template_folder='templates')


@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    """
    Method to login user, checks  password and username
    """
    db = DbManager()
    if current_user.is_anonymous:
        form = LoginForm()
        if form.validate_on_submit():
            try:
                # see if user exists
                user = db.get_user(form.email.data)
            except UserNotFoundError:
                # create an empty user
                user = None
                pass

            # Checks the users credentials
            if not user or not db.verify_password(user.email, form.password.data):
                flash("Invalid login")
                return render_template('users/login.html', form=form)
            else:
                # Log the user in
                login_user(user)
                # Redirect based on user role
                if current_user.access_level == 'user':
                    return redirect(url_for('users.account'))
                elif current_user.access_level == 'admin':
                    return redirect(url_for('admin.admin'))
                else:
                    # Redirect to a default page if user role is not defined
                    return redirect(url_for('main.index'))
            # Add a return statement here to handle the case when form is not submitted
        return render_template('users/login.html', form=form)
    else:
        # Displays error message
        flash("You are already logged in.")
        return redirect(url_for('index'))


@users_blueprint.route('/register', methods=['GET', 'POST'])
@login_required
@access_level_required('admin')
def register_staff():
    """Method to register a new staff member or admin"""
    db = DbManager()

    # create signup form object
    form = RegisterForm()

    # if request method is POST or form is valid
    if form.validate_on_submit():
        try:
            # see if user exists
            user = db.get_user(form.email.data)
        except UserNotFoundError:
            # create an empty user
            user = None
            pass
        # if this returns a user, then the email already exists in database

        # if email already exists redirect user back to signup page with error message so user can try again
        if user:
            flash('Email address already exists')
            return render_template('users/../templates/admin/add_staff.html', form=form)

        # create a new user with the form data
        db.add_staff(form.email.data, form.password.data, "user")
        return redirect(url_for('users.login'))

    return render_template('users/../templates/admin/add_staff.html', form=form)


@users_blueprint.route('/logout')
@login_required
def logout():
    """Method to log out user"""
    logout_user()
    return redirect(url_for('index'))


@users_blueprint.route('/update_password', methods=['GET', 'POST'])
@login_required
def update_password():
    """Method to update a users password"""
    db = DbManager()

    form = UpdatePasswordForm()
    # validate submitted ChangePasswordForm
    if form.validate_on_submit():
        msg = db.change_password(current_user.user_id, form.current_password.data, form.new_password.data)
        if msg == "wrong password":
            flash('Incorrect current password.')
            return render_template('users/update_password.html', form=form)
        if msg == "same password":
            flash('New password must be different from the current password.')
            return render_template('users/update_password.html', form=form)
        flash('Password has been changed successfully.')
        return redirect(url_for('users.account'))

    return render_template('users/update_password.html', form=form)


@users_blueprint.route('/account')
@login_required
def account():
    """Method to return account page with users details"""
    return render_template('users/account.html',
                           user_id=current_user.user_id,
                           email=current_user.email,
                           access_level=current_user.access_level)


@users_blueprint.route('/request_info')
def request_info():
    """Method to show products that have a low stock"""
    low_stock_products = DbManager.get_required_stock()
    return render_template('main/index.html', products=low_stock_products)

templates/Error400.html
<!-- Written by Megat Aiman -->
{% extends 'base.html' %}

{% block content %}
    <!--Error Message-->
    <h2 class="title is-2">400 Bad Request: Sorry, your request is invalid or malformed.
        Please check your input and try again.</h2>

    <!-- External Page Link -->
    <p>For more information, visit <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400">400 Bad Request</a>.</p>
{% endblock %}

templates/Error403.html
<!-- Written by Megat Aiman -->
{% extends 'base.html' %}

{% block content %}
    <!--Error Message-->
    <h2 class="title is-2">403 Forbidden: Oops! You don't have permission to access this resource.
        If you believe this is an error, please contact the administrator.</h2>

    <!-- External Page Link -->
    <p>For more information, visit <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403">403 Forbidden</a>.</p>
{% endblock %}

templates/Error404.html
<!-- Written by Megat Aiman -->
{% extends 'base.html' %}

{% block content %}
    <!--Error Message-->
    <h2 class="title is-2">404 Not Found: The page you're looking for doesn't exist.
        Double-check the URL or navigate to a different page.</h2>

    <!-- External Page Link -->
    <p>For more information, visit <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404">404 Not Found</a>.</p>
{% endblock %}

templates/Error500.html
<!-- Written by Megat Aiman -->
{% extends 'base.html' %}

{% block content %}
    <!--Error Message-->
    <h2 class="title is-2">500 Internal Server Error: Something went wrong on our end. We apologise for the inconvenience.
        Our team has been notified of the issue.</h2>

    <!-- External Page Link -->
    <p>For more information, visit <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500">500 Internal Server Error</a>.</p>
{% endblock %}

templates/base.html
<!-- Written by Daniel Cook, Megat Aiman, Daniel Ellam -->
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet"> <!-- Roboto font from Google -->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;700&display=swap" rel="stylesheet"> <!-- Montserrat font from Google -->
    <link rel="stylesheet" href="{{ url_for('static', filename= 'css/style.css') }}">
    <title>{% block title %} {% endblock %}</title>
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v19.0" nonce="jv5lmxx7"></script>
  </head>
      <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap">
  <body>
    {% if blue_panel %}
        <div class="blue-panel"></div>
    {% endif %}
    <nav class="navbar navbar-expand-md navbar-light custom-navbar">
        <div id="navbarMenuHeroA" class="navbar-menu">
            <div class="navbar-end align-items-center">
                <a href="{{ url_for('index') }}" class="navbar-item btn-link"> Home </a>
                {% if current_user.is_authenticated %}
                    <a href="{{ url_for('users.account') }}" class="navbar-item btn-link"> Account </a>
                    <a href="{{ url_for('database.database')}}" class="navbar-item btn-link" >Database</a>

                    {% if current_user.access_level == 'admin' %}
                         <a href="{{ url_for('admin.admin')}}" class="navbar-item btn-link"> Admin </a>
                        {% endif %}
                {% else %}
                    <a href="{{ url_for('users.login')}}" class="navbar-item btn-link"> Login </a>
                {% endif %}
                {%  if current_user.is_authenticated %}
                    <a href="{{ url_for('users.logout')}}" class="navbar-item btn-link">Logout</a>
                {% endif %}
            </div>
        </div>
    </nav>
    <div class="container" style="padding-top: 80px;">
        {% block content %} {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/htmx.org@1.9.4"></script>
  </body>
</html>