users/forms.py
# File written by Daniel C, Megat
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, EmailField, BooleanField
from wtforms.validators import Email, ValidationError, Length, EqualTo, DataRequired, Regexp
import re


# Checks for not allowed characters
def character_check(form, field):
    excluded_chars = "*?!'^+%&/()=}][{$#@<>"

    for char in field.data:
        if char in excluded_chars:
            raise ValidationError(f"Character {char} is not allowed")


# Checks for if the phone number is in the correct format
def validate_phone(self, phone):
    p = re.compile("[0-9]{4}\-[0-9]{3}\-[0-9]{4}")
    if not p.match(phone.data):
        raise ValidationError("Phone number must be in the format XXXX-XXX-XXXX")


# Looks for a digit in the password
def validate_digit(self, field):
    count = 0
    digits = "0123456789"
    for char in field.data:
        if char in digits:
            count = count + 1
    if count == 0:
        raise ValidationError("Password must contain a digit")


# Checks for a lowercase letter in the password
def lowercase_check(form, field):
    lowercase_valid = False
    for char in field.data:
        if char.islower():
            lowercase_valid = True
    if not lowercase_valid:
        raise ValidationError("Password must contain a lowercase letter")


# Check for an uppercase letter in the password
def uppercase_check(form, field):
    uppercase_valid = False
    for char in field.data:
        if char.isupper():
            uppercase_valid = True
    if not uppercase_valid:
        raise ValidationError("Password must contain an uppercase letter")


# Checks for a special character in the password
def special_character_check(self, password):
    p = re.compile(r'(?=.*\W)')
    if not p.match(password.data):
        raise ValidationError("Password must contain a special character")


# Checks the date of birth is in the correct format
def validate_DOB(self, DOB):
    p = re.compile("^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[0-2])/(19|20)\d{2}$")
    if not p.match(DOB.data):
        raise ValidationError("DOB must be in the format DD/MM/YYYY, and have appropriate digits")


# Checks if the postcode is in the correct format
def validate_postcode(self, postcode):
    validated = False
    p1 = re.compile("[A-Z]{1}[0-9]{1}\s[0-9]{1}[A-Z]{2}")
    p2 = re.compile("[A-Z]{1}[0-9]{2}\s[0-9]{1}[A-Z]{2}")
    p3 = re.compile("[A-Z]{2}[0-9]{1}\s[0-9]{1}[A-Z]{2}")
    if p1.match(postcode.data):
        validated = True
    if p2.match(postcode.data):
        validated = True
    if p3.match(postcode.data):
        validated = True
    if not validated:
        raise ValidationError("Postcode must be in one of these formats: D7 8SG, D78 8SG, DL7 8SG")


# Checks the pin is in the correct format
def validate_pin(self, pin):
    p = re.compile("[0-9]{6}")
    if not p.match(pin.data):
        raise ValidationError("Pin is 6 digits long")


# The register form with validators
class LoginForm(FlaskForm):
    email = StringField(validators=[DataRequired(), Email()])
    password = PasswordField(validators=[DataRequired()])
    submit = SubmitField()

class RegisterForm(FlaskForm):
    password_validation = r'^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^a-zA-Z\d])(?=.*[a-zA-Z\d\S])'

    email = EmailField(validators=[Email(),DataRequired()])
    password = PasswordField(
        validators=[Length(min=6, message = "Length of password must be a minimum of 6 characters."),
                    Regexp(password_validation,
                           message="Password must contain at least 1 digit, at least 1 lowercase and at least 1 "
                                   "uppercase word character, and at least 1 special character"), DataRequired()])
    confirm_password = PasswordField(validators=[EqualTo('password', message="The confirm password does not match."),DataRequired()])
    submit = SubmitField()

class UpdatePasswordForm(FlaskForm):
    password_validation = r'^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^a-zA-Z\d])(?=.*[a-zA-Z\d\S])'

    current_password = PasswordField('Current Password', id='password', validators=[DataRequired()])
    show_password = BooleanField('Show Password', id='check')
    new_password = PasswordField('New Password', validators=[DataRequired(), Length(min=6, message="Length of password must be a minimum of 6 characters."), Regexp(password_validation, message="Password must contain at least 1 digit, at least 1 lowercase and at least 1 uppercase word character, and at least 1 special character")])
    confirm_new_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('new_password', message="Password confirmation must match the new password")])
    submit = SubmitField('Change Password')

users/views.py
# File written by Daniel, Megat, Louis, Asha
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import login_user, current_user, login_required, logout_user
from app import access_level_required
from users.forms import LoginForm, RegisterForm, UpdatePasswordForm
from Database_Manager.db_crud import DbManager, UserNotFoundError

users_blueprint = Blueprint('users', __name__, template_folder='templates')


@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    """
    Method to login user, checks  password and username
    """
    db = DbManager()
    if current_user.is_anonymous:
        form = LoginForm()
        if form.validate_on_submit():
            try:
                # see if user exists
                user = db.get_user(form.email.data)
            except UserNotFoundError:
                # create an empty user
                user = None
                pass

            # Checks the users credentials
            if not user or not db.verify_password(user.email, form.password.data):
                flash("Invalid login")
                return render_template('users/login.html', form=form)
            else:
                # Log the user in
                login_user(user)
                # Redirect based on user role
                if current_user.access_level == 'user':
                    return redirect(url_for('users.account'))
                elif current_user.access_level == 'admin':
                    return redirect(url_for('admin.admin'))
                else:
                    # Redirect to a default page if user role is not defined
                    return redirect(url_for('main.index'))
            # Add a return statement here to handle the case when form is not submitted
        return render_template('users/login.html', form=form)
    else:
        # Displays error message
        flash("You are already logged in.")
        return redirect(url_for('index'))


@users_blueprint.route('/register', methods=['GET', 'POST'])
@login_required
@access_level_required('admin')
def register_staff():
    """Method to register a new staff member or admin"""
    db = DbManager()

    # create signup form object
    form = RegisterForm()

    # if request method is POST or form is valid
    if form.validate_on_submit():
        try:
            # see if user exists
            user = db.get_user(form.email.data)
        except UserNotFoundError:
            # create an empty user
            user = None
            pass
        # if this returns a user, then the email already exists in database

        # if email already exists redirect user back to signup page with error message so user can try again
        if user:
            flash('Email address already exists')
            return render_template('users/../templates/admin/add_staff.html', form=form)

        # create a new user with the form data
        db.add_staff(form.email.data, form.password.data, "user")
        return redirect(url_for('users.login'))

    return render_template('users/../templates/admin/add_staff.html', form=form)


@users_blueprint.route('/logout')
@login_required
def logout():
    """Method to log out user"""
    logout_user()
    return redirect(url_for('index'))


@users_blueprint.route('/update_password', methods=['GET', 'POST'])
@login_required
def update_password():
    """Method to update a users password"""
    db = DbManager()

    form = UpdatePasswordForm()
    # validate submitted ChangePasswordForm
    if form.validate_on_submit():
        msg = db.change_password(current_user.user_id, form.current_password.data, form.new_password.data)
        if msg == "wrong password":
            flash('Incorrect current password.')
            return render_template('users/update_password.html', form=form)
        if msg == "same password":
            flash('New password must be different from the current password.')
            return render_template('users/update_password.html', form=form)
        flash('Password has been changed successfully.')
        return redirect(url_for('users.account'))

    return render_template('users/update_password.html', form=form)


@users_blueprint.route('/account')
@login_required
def account():
    """Method to return account page with users details"""
    return render_template('users/account.html',
                           user_id=current_user.user_id,
                           email=current_user.email,
                           access_level=current_user.access_level)


@users_blueprint.route('/request_info')
def request_info():
    """Method to show products that have a low stock"""
    low_stock_products = DbManager.get_required_stock()
    return render_template('main/index.html', products=low_stock_products)

templates/users/account.html
<!-- Written by Daniel Cook, Megat Aiman -->
{% extends "base.html" %}

{% block content %}

<!-- Header -->
<div class="column is-6 is-offset-3">
    <h1 class="center-h1">Your Account</h1>

    <!-- User information table -->
    <h1 class="subheader-is-center"> Account Information </h1>
        <div class="box">
        <table class="accounts-table">
        <tbody>
            <tr>
                <th>User ID</th>
                <th>{{ user_id }}</th>
            </tr>
            <tr>
                <th>Email</th>
                <th>{{ email }}</th>
            </tr>
        </tbody>
        </table>
        </div>
    <h1 class="subheader-is-center"> Account Privilege </h1>
        <div class="box">
        <table class="accounts-table">
        <tbody>
            <tr>
                <th>Access Level</th>
                <th>{{ access_level }}</th>
            </tr>
        </tbody>
        </table>
        </div>

    <!-- Change password -->
    <h1 class="subheader-is-center"> Password and Security </h1>
    <div class="box">
        <table class="accounts-table">
            <tbody>
            <tr>
                <th>Password</th>
                <th><a class="change-pw-btn" href="{{ url_for('users.update_password') }}">Change Password</a></th>
            </tr>
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

templates/users/login.html
<!-- Written by Daniel Cook, Megat Aiman -->
{% extends "base.html" %}

{% block content %}

    <!-- Header -->
    <div class="column is-5 is-offset-4">
        <h1 class="center-h1">Login</h1>

        <!-- Login form -->
        <div class="box">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <div class="center-flash">
                        {{ messages[0] }}
                    </div>
                {% endif %}
            {% endwith %}
                <form method="POST">
                    <div class="field">
                        {{ form.csrf_token() }}
                        <div class="control">
                            {{ form.email(class="center-input", placeholder="Email") }}
                            {% for error in form.email.errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    </div>
                    <div class="field">
                        <div class="control">
                            {{ form.password(class="center-input", placeholder="Password") }}
                        </div>
                    </div>
                    <div>
                        {{ form.submit(class="button is-info is-centered") }}
                    </div>
                </form>
        </div>
    </div>
{% endblock %}

templates/users/register.html
{% extends "base.html" %}

{% block content %}
    <div class="column is-5 is-offset-4">
        <h3 class="title is-3">Register</h3>
        <div class="box">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <div class="notification is-danger">
                        {{ messages[0] }}. Go to <a href="{{ url_for('users.login') }}">login page</a>.
                    </div>
                {% endif %}
            {% endwith %}
            <form method="POST">
                <div class="field">
                    {{ form.csrf_token() }}
                    <div class="control">
                        {{ form.email(class="input", placeholder="Email") }}
                        {% for error in form.email.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.password(class="input", placeholder="Password") }}
                        {% for error in form.password.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.confirm_password(class="input", placeholder="Confirm Password") }}
                        {% for error in form.confirm_password.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>
                <div>
                    {{ form.submit(class="button is-info is-centered") }}
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/users/register_staff.html
{% extends "base.html" %}

{% block content %}
    <div class="column is-5 is-offset-4">
        <h1 class="title is-3">Register New Staff</h1>
        <div class="box">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <div class="notification is-danger">
                        {{ messages[0] }}. Go to <a href="{{ url_for('users.login') }}">login page</a>.
                    </div>
                {% endif %}
            {% endwith %}
            <form method="POST">
                <div class="field">
                    {{ form.csrf_token() }}
                    <div class="control">
                        {{ form.email(class="input", placeholder="Email") }}
                        {% for error in form.email.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.password(class="input", placeholder="Password") }}
                        {% for error in form.password.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.confirm_password(class="input", placeholder="Confirm Password") }}
                        {% for error in form.confirm_password.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>
                <div>
                    {{ form.submit(class="button is-info is-centered") }}
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/users/update_password.html
<!-- Written by Daniel Cook, Megat Aiman, Asha Smeaton -->
{% extends 'base.html' %}

{% block content %}

    <script type="text/javascript" src="{{ url_for('static', filename='listeners.js') }}"></script>

    <!-- Header -->
    <div class="column is-5 is-offset-4">
        <h1 class="center-h1">Change Password</h1>

        <!-- Change password form -->
        <br>
        <br>
        <div class="box">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <div class="center-flash">
                        {{ messages[0] }}
                    </div>
                {% endif %}
            {% endwith %}
            <form method="POST">
                <div class="field">
                    {{ form.csrf_token() }}
                    <div class="control">
                        {{ form.current_password(class="center-input", placeholder="Current Password") }}
                        {% for error in form.current_password.errors %}
                            <div class="center-flash">
                                {{ error }}
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.show_password() }}
                        {{ form.show_password.label }}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.new_password(class="center-input", placeholder="New Password") }}
                        {% for error in form.new_password.errors %}
                            <div class="center-flash">
                                {{ error }}
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {{ form.confirm_new_password(class="center-input", placeholder="Confirm New Password") }}
                        {% for error in form.confirm_new_password.errors %}
                            <div class="center-flash">
                                {{ error }}
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div>
                    {{ form.submit(class="button is-info is-centered") }}
                </div>
            </form>
        </div>
    </div>
{% endblock %}